import { existsSync, readdirSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import type { DefaultTheme } from 'vitepress'

// Sidebar/nav for the private overlay (docs/private/, its own private repo).
// Unlike the curated public sidebar, this one is generated by scanning the
// directory: a quick note dropped into inbox/ shows up with zero maintenance.
// Only used when WIKI_PRIVATE=1 — the public build never calls into this.

const PRIVATE_DIR = fileURLToPath(new URL('../private', import.meta.url))

/** Files that are repo meta, not wiki content. */
const EXCLUDED_FILES = new Set(['README.md'])

export function hasPrivateContent(): boolean {
  return existsSync(join(PRIVATE_DIR, 'index.md'))
}

export function privateNav(): DefaultTheme.NavItem[] {
  return [{ text: '🔒 Private', link: '/private/' }]
}

export function privateSidebar(): DefaultTheme.SidebarItem[] {
  const sections: DefaultTheme.SidebarItem[] = []

  // Top-level pages directly under private/ (e.g. the landing page).
  const rootItems = mdFilesIn(PRIVATE_DIR)
    .filter((f) => f !== 'index.md')
    .map((f) => itemFor(PRIVATE_DIR, '', f))

  // One collapsed group per subdirectory, index.md first.
  const groups = subdirsOf(PRIVATE_DIR).map((dir) => {
    const dirPath = join(PRIVATE_DIR, dir)
    const files = mdFilesIn(dirPath)
    const items: DefaultTheme.SidebarItem[] = []
    if (files.includes('index.md')) items.push(itemFor(dirPath, dir, 'index.md'))
    for (const f of files.filter((f) => f !== 'index.md').sort()) {
      items.push(itemFor(dirPath, dir, f))
    }
    return { text: sectionTitle(dir), collapsed: true, items }
  })

  sections.push({
    text: '🔒 Private',
    collapsed: false,
    items: [{ text: 'Overview', link: '/private/' }, ...rootItems, ...groups],
  })
  return sections
}

function subdirsOf(dir: string): string[] {
  return readdirSync(dir, { withFileTypes: true })
    .filter((e) => e.isDirectory() && !e.name.startsWith('.') && e.name !== 'node_modules')
    .map((e) => e.name)
    .sort()
}

function mdFilesIn(dir: string): string[] {
  return readdirSync(dir, { withFileTypes: true })
    .filter((e) => e.isFile() && e.name.endsWith('.md') && !EXCLUDED_FILES.has(e.name))
    .map((e) => e.name)
}

function itemFor(dirPath: string, dir: string, file: string): DefaultTheme.SidebarItem {
  const slug = file.replace(/\.md$/, '')
  const base = dir ? `/private/${dir}` : '/private'
  const link = slug === 'index' ? `${base}/` : `${base}/${slug}`
  return { text: pageTitle(join(dirPath, file), slug), link }
}

/** Title from the first `# heading` (or `title:` frontmatter), falling back to the filename. */
function pageTitle(filePath: string, slug: string): string {
  try {
    const src = readFileSync(filePath, 'utf8')
    // Extract the frontmatter fence first (anchored to the start of the file,
    // no `m` flag), then look for title: inside it only — a naive multiline
    // regex can match `---` hr lines or "title:"-looking body text instead.
    const block = src.match(/^---\r?\n([\s\S]*?)\r?\n---(?:\r?\n|$)/)
    if (block) {
      const t = block[1].match(/^title:[ \t]*["']?(.+?)["']?[ \t]*$/m)
      if (t) return t[1]
    }
    const h1 = src.match(/^#\s+(.+?)\s*$/m)
    if (h1) return stripMarkdown(h1[1])
  } catch {
    /* fall through to filename */
  }
  return slug === 'index' ? 'Overview' : sectionTitle(slug)
}

function stripMarkdown(text: string): string {
  return text.replace(/[*_`]/g, '').replace(/\[(.+?)\]\(.+?\)/g, '$1').trim()
}

function sectionTitle(slug: string): string {
  const words = slug.replace(/[-_]/g, ' ').trim()
  return words.charAt(0).toUpperCase() + words.slice(1)
}
